Ignore return values when a filter callback is abstract
Automattic/VIP-Coding-Standards pull request #581
Opened 2020-09-08 20:03 UTC by kevinfodness

If a filter is defined in the constructor of an abstract class, and uses an abstract method as its callback, relying on implementing classes to define the return value, the `WordPressVIPMinimum.Hooks.AlwaysReturnInFilter.MissingReturnStatement` sniff causes phpcs to crash.

This PR adds a unit test to confirm the issue, and implements a fix using the same code that is used by phpcs itself.

Fixes #580

2020-09-09 07:17 UTC, GaryJones commented on WordPressVIPMinimum/Sniffs/Hooks/AlwaysReturnInFilterSniff.php
> +		if ( false === isset( $this->tokens[ $stackPtr ]['scope_closer'] ) ) {
```suggestion
		if ( isset( $this->tokens[ $stackPtr ]['scope_closer'] ) === false ) {
```

2020-09-09 08:21 UTC, GaryJones commented on WordPressVIPMinimum/Sniffs/Hooks/AlwaysReturnInFilterSniff.php
> +		 * Stop if the constructor doesn't have a body, like when it is abstract.
```suggestion
		 * Stop if the function doesn't have a body, like when it is abstract.
```

2020-09-09 15:33 UTC, jrfnl commented
I've added two additional commits to this PR, updating the unit tests and implementing my suggestion from https://github.com/Automattic/VIP-Coding-Standards/issues/580#issuecomment-689119006

2020-09-09 16:14 UTC, GaryJones commented on WordPressVIPMinimum/Sniffs/Hooks/AlwaysReturnInFilterSniff.php
> +		$methodProps = $this->phpcsFile->getMethodProperties($stackPtr);
```suggestion
		$methodProps = $this->phpcsFile->getMethodProperties( $stackPtr );
```

2020-09-09 16:15 UTC, GaryJones commented on WordPressVIPMinimum/Sniffs/Hooks/AlwaysReturnInFilterSniff.php
> +		if ($methodProps['is_abstract'] === true) {
```suggestion
		if ( $methodProps['is_abstract'] === true ) {
```

2020-09-09 16:17 UTC, GaryJones commented
Noting that the new Warning will now appear when there was no warning previously (which was a false negative due to the lack of support for short array syntax).

2020-09-09 16:24 UTC, jrfnl commented
> Noting that the new Warning will now appear when there was no warning previously (which was a false negative due to the lack of support for short array syntax).

Correct. I've also given it a separate error code on purpose with that in mind. Semver-wise, it should probably go into a minor rather than a patch version as it can be seen as a new feature.

2020-09-11 18:40 UTC, rebeccahum requested changes

2020-09-11 18:40 UTC, rebeccahum commented on WordPressVIPMinimum/Sniffs/Hooks/AlwaysReturnInFilterSniff.php
> +			$message = 'The callback for the `%s` filter hook-in points to an abstract method. Please, make sure that all child class implementations of this abstract method always return a value.';
```suggestion
			$message = 'The callback for the `%s` filter hook-in points to an abstract method. Please ensure that child class implementations of this abstract method always return a value.';
```

2020-09-13 09:37 UTC, GaryJones approved these changes

2020-09-14 15:55 UTC, rebeccahum approved these changes

2020-09-14 15:55 UTC, merged