Docs/install update
Automattic/VIP-Coding-Standards pull request #808
Opened 2024-02-02 19:24 UTC by terriann

*  Include `--dev` in require commands
* Use the full term `global` instead of the shorthand `g`
* Mirror the "Installation" section structure to the structure on WordPress/WordPress-Coding-Standards

2024-02-03 04:28 UTC, jrfnl commented on README.md
> +composer config allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
```suggestion
composer global config allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
```

2024-02-07 14:19 UTC, GaryJones requested changes
One little fix, then ✅

2024-02-07 14:19 UTC, GaryJones commented on README.md
> +Please refer to the [installation instructions for installing PHP_CodeSniffer for WordPress.com VIP](https://docs.wpvip.com/how-tos/code-review/php_codesniffer/) for more details.
```suggestion
Please refer to the [installation instructions for installing PHP_CodeSniffer for WordPress VIP](https://docs.wpvip.com/how-tos/code-review/php_codesniffer/) for more details.
```

2024-02-16 16:09 UTC, GaryJones approved these changes

2024-02-16 16:09 UTC, merged